Apple.com branch
Rumbie-Mudzie7/Project-Apple.com pull request #3
Opened 2020-04-13 07:54 UTC by Rumbie-Mudzie7

The Apple.com project primarily focused on backgrounds and gradients.  As required, a background image was placed and linear gradient was used for the header.

2020-04-13 08:32 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-04-13 08:43 UTC, mikenath223 commented on index.html
> +        />
Instead of images make these to be text elements. We want to avoid using text snapshots of the page. Kindly fix this.

2020-04-13 08:43 UTC, mikenath223 commented on index.html
> +      <div><img src="./images/iPhone-image4.jpg" alt="iPhone-advert" /></div>
As this project is background and gradients based please remove these images and make them background images instead.

2020-04-13 08:44 UTC, mikenath223 requested changes
### Hi @Rumbie-Mudzie7 👋

Your project looks quite cool.👌

However, kindly make the following changes to make it look awesome:

- [ ] Required - The search icon in the navbar needs to be placed in the search input field as a background.
**This is yours👇**
![ice_screenshot_20200413-093339](https://user-images.githubusercontent.com/33323077/79107086-a3205800-7d6b-11ea-85a5-d207014ae706.png)

**This is the way it should be👇**
![ice_screenshot_20200413-093442](https://user-images.githubusercontent.com/33323077/79107206-e4b10300-7d6b-11ea-885a-1746dec8c138.png)

- [ ] Required - Also ensure you center the text in your navbar items, just as it looks in the original and also make the apple logo to the left of the navbar larger in size.
**This is yours👇**
![ice_screenshot_20200413-093352](https://user-images.githubusercontent.com/33323077/79107356-2477ea80-7d6c-11ea-9a65-4a472c1da055.png)

**This is the way it should be👇**
![ice_screenshot_20200413-093512](https://user-images.githubusercontent.com/33323077/79107393-322d7000-7d6c-11ea-8216-be31bd7c1d8b.png)


ALSO, REFER TO THE INLINE COMMENTS IN YOUR CODE BELOW. KEEP SCROLLING👇

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

KINDLY KEEP SCROLLING👇

2020-04-13 23:51 UTC, Dandush03 commented
# :red_circle: Status: Required Changes :red_circle:
### Hey :wave: 

### From what i see you haven't fix anything regarding the last comment of my college @mikenath223. if you need any help, don't hesitate to contact me through slack

## Kindly address all these changes stated before and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

2020-04-14 23:56 UTC, mikenath223 requested changes
### Hello again 👋

Your project looks more improved compared to the previous state.
Nice job working on the items stated in the previous reviews.👌

You are almost there just one more adjustment needs to be made.

Kindly, hang in there. You've got this.👍

- [ ] Required -  Your page looks quite different from the original one based on this:
**THIS IS YOURS👇**
![ice_screenshot_20200415-004008](https://user-images.githubusercontent.com/33323077/79284593-08329580-7eb3-11ea-80b2-d4826e131193.png)

**THIS IS THE ORIGINAL PAGE👇**
![ice_screenshot_20200415-005238](https://user-images.githubusercontent.com/33323077/79284745-7c6d3900-7eb3-11ea-9b3d-aaa01477586b.png)

There is a white border at the left of your page without a corresponding right border on the page. Kindly fix this by adding a margin to the right of the page.

- [ ] Required - Also fix the four bottom images they are overflowing the page width. Kindly adjust them so that they look exactly like the original page.

**You are almost there @Rumbie-Mudzie7 👏**

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-15 06:50 UTC, Rumbie-Mudzie7 commented
Good day

Thank you for the feedback and helpful tips. Will work on it now and get
back to you.

On Wed, Apr 15, 2020 at 1:56 AM Michgolden Ukeje <notifications@github.com>
wrote:

> *@mikenath223* requested changes on this pull request.
> Hello again 👋
>
> Your project looks more improved compared to the previous state.
> Nice job working on the items stated in the previous reviews.👌
>
> You are almost there just one more adjustment needs to be made.
>
> Kindly, hang in there. You've got this.👍
>
>    - Required - Your page looks quite different from the original one
>    based on this:
>    *THIS IS YOURS👇*
>    [image: ice_screenshot_20200415-004008]
>    <https://user-images.githubusercontent.com/33323077/79284593-08329580-7eb3-11ea-80b2-d4826e131193.png>
>
> *THIS IS THE ORIGINAL PAGE👇*
> [image: ice_screenshot_20200415-005238]
> <https://user-images.githubusercontent.com/33323077/79284745-7c6d3900-7eb3-11ea-9b3d-aaa01477586b.png>
>
> There is a white border at the left of your page without a corresponding
> right border on the page. Kindly fix this by adding a margin to the right
> of the page.
>
>    - Required - Also fix the four bottom images they are overflowing the
>    page width. Kindly adjust them so that they look exactly like the original
>    page.
>
> *You are almost there @Rumbie-Mudzie7 <https://github.com/Rumbie-Mudzie7>
> 👏*
>
> Kindly fix these issues and request another review👍
> Feel free to contact me on slack(michgolden) if you need further
> clarification.
>
> HAPPY CODING👨‍💻
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Rumbie-Mudzie7/Project-Apple.com/pull/3#pullrequestreview-393371553>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALQFOEIDYGKC6T5RWZGPLADRMTZ25ANCNFSM4MGZDUEQ>
> .
>

2020-04-15 09:26 UTC, lekegitrepo commented
### Hi @Rumbie-Mudzie7 👏 💯
### You have done a good job by implementing required changes. This project is approved. Good luck with the next project.

### Reviewed by Temitayo Adeleke
- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

2020-04-15 09:27 UTC, lekegitrepo approved these changes
### Status: Approved

2020-04-15 09:35 UTC, Rumbie-Mudzie7 commented
Thank you for your response Temitayo.

On Wed, Apr 15, 2020 at 11:27 AM Temitayo Adeleke <notifications@github.com>
wrote:

> *@lekegitrepo* approved this pull request.
> Status: Approved
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Rumbie-Mudzie7/Project-Apple.com/pull/3#pullrequestreview-393605525>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALQFOEJ7DOXHNKKWEI4VI7TRMV4YPANCNFSM4MGZDUEQ>
> .
>

2020-04-15 09:44 UTC, merged